name: Build All AAP Image Flavors

on:
  workflow_dispatch:

env:
  PACKER_VERSION: "latest" # or: "latest"
  PACKER_FILE: ./images/packer/aap.pkr.hcl

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flavor: [C, CE, CH, CEH]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: GCP auth setup
        uses: google-github-actions/auth@v0 
        with:
          credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ${{ env.PACKER_FILE }}"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ${{ env.PACKER_FILE }}"

      - name: Set build variables based on flavor
        run: |
          if [[ "${{ matrix.flavor }}" == "C" ]]; then
            export AAP_INCLUDE_CONTROLLER=true
            export AAP_INCLUDE_EDA_CONTROLLER=false
            export AAP_INCLUDE_AUTOMATION_HUB=false
          elif [[ "${{ matrix.flavor }}" == "CE" ]]; then
            export AAP_INCLUDE_CONTROLLER=true
            export AAP_INCLUDE_EDA_CONTROLLER=true
            export AAP_INCLUDE_AUTOMATION_HUB=false
          elif [[ "${{ matrix.flavor }}" == "CH" ]]; then
            export AAP_INCLUDE_CONTROLLER=true
            export AAP_INCLUDE_EDA_CONTROLLER=false
            export AAP_INCLUDE_AUTOMATION_HUB=true
          elif [[ "${{ matrix.flavor }}" == "CEH" ]]; then
            export AAP_INCLUDE_CONTROLLER=true
            export AAP_INCLUDE_EDA_CONTROLLER=true
            export AAP_INCLUDE_AUTOMATION_HUB=true
          fi

          echo "AAP_INCLUDE_CONTROLLER=${AAP_INCLUDE_CONTROLLER}" >> $GITHUB_ENV
          echo "AAP_INCLUDE_EDA_CONTROLLER=${AAP_INCLUDE_EDA_CONTROLLER}" >> $GITHUB_ENV
          echo "AAP_INCLUDE_AUTOMATION_HUB=${AAP_INCLUDE_AUTOMATION_HUB}" >> $GITHUB_ENV

      - name: Build AAP Image
        run: |
          packer build -var "aap_include_controller=${AAP_INCLUDE_CONTROLLER}" \
                       -var "aap_include_eda_controller=${AAP_INCLUDE_EDA_CONTROLLER}" \
                       -var "aap_include_automation_hub=${AAP_INCLUDE_AUTOMATION_HUB}" \
                       ${{ env.PACKER_FILE }}